services:
  plannerbot:
    build: .
    container_name: plannerbot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - plannerbot_db:/data

volumes:
  plannerbot_db:
    name: plannerbot_db
